[package]
name = "secret-toolkit-storage"
version = "0.10.0"
edition = "2021"
authors = ["SCRT Labs <info@scrtlabs.com>"]
license-file = "../../LICENSE"
repository = "https://github.com/scrtlabs/secret-toolkit"
readme = "Readme.md"
description = "Abstractions over storage in Secret Contracts"
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["secret-network", "secret-contracts", "secret-toolkit"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
secret-toolkit-serialization = { version = "0.10.0", path = "../serialization" }
