[package]
name = "secret-toolkit-snip20"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", rev = "004c6bc" }
secret-toolkit-utils = { path = "../utils" }
schemars = "0.7"
