[package]
name = "secret-toolkit-snip20"
version = "0.8.1"
edition = "2021"
authors = ["SCRT Labs <info@scrtlabs.com>"]
license-file = "../../LICENSE"
repository = "https://github.com/scrtlabs/secret-toolkit"
readme = "Readme.md"
description = "Boilerplate for using SNIP-20 contracts on Secret Network"
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["secret-network", "secret-contracts", "secret-toolkit"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = { workspace = true }
schemars = { workspace = true }
cosmwasm-std = { workspace = true }
secret-toolkit-utils = { version = "0.8", path = "../utils" }
