[package]
name = "secret-toolkit-crypto"
version = "0.10.1"
edition = "2021"
authors = ["SCRT Labs <info@scrtlabs.com>"]
license-file = "../../LICENSE"
repository = "https://github.com/scrtlabs/secret-toolkit"
readme = "Readme.md"
description = "Cryptographic tools for writing Secret Contracts"
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["secret-network", "secret-contracts", "secret-toolkit"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["hash", "ecc-secp256k1", "rand"]
hash = ["sha2"]
ecc-secp256k1 = ["secp256k1"]
rand = ["hash", "rand_chacha", "rand_core"]

[dependencies]
rand_core = { version = "0.6.4", default-features = false, optional = true }
rand_chacha = { version = "0.3.1", default-features = false, optional = true }
sha2 = { version = "0.10.6", default-features = false, optional = true }
secp256k1 = { version = "0.27.0", default-features = false, features = [
    "alloc",
], optional = true }
cosmwasm-std = { workspace = true }
cc = { version = "=1.1.10" }

[dev-dependencies]
secp256k1 = { version = "0.27.0", default-features = false, features = [
    "alloc",
    "rand-std",
] }
base64 = "0.21.0"
